{
    "name": "Employee Customisation BHM",
    "version": "17.0.1.0.0",
    "summary": "Employee Customisation BHM",
    "description": "Employee Customisation BHM",
    "author": "Hynsys Technologies",
    "website": "https://www.hynsys.com",
    "license": "OPL-1",
    "category": "Human Resources",
    "depends": [
        "hr",
        # "hy_user_defaults",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/ir_sequence_data.xml",
        "data/mail_activity_type_data.xml",
        "views/res_users_views.xml",
        "views/employee_visit_form_views.xml",
        "views/employee_penalty_form_views.xml",
        "views/employee_request_form_views.xml",
        "views/trip_allowance_form_views.xml",
        "views/employee_bonus_form_views.xml",
        "views/penalty_notice_form_views.xml",
        "views/employee_salary_form_views.xml",
        "views/employee_overtime_form_views.xml",
        "views/employee_custody_form_views.xml",
        "views/hr_employee_views.xml",
        "views/employee_custody_type.xml",
    ],
    "auto_install": False,
    "application": False,
}
